apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: bunseki
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend
          ports:
            - containerPort: 52523
